In [14]:
#importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
from skleran.model_selection import train_test_split

ModuleNotFoundError: No module named 'skleran'

In [4]:
iris=pd.read_csv('iris_csv.csv')
iris.tail()

sepallength  sepalwidth  petallength  petalwidth           class
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

In [5]:
iris['class'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: class, dtype: int64

In [5]:
iris['class'].value_counts()

Iris-versicolor    50
Iris-virginica     50
Iris-setosa        50
Name: class, dtype: int64

In [6]:
iris.columns

Index(['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'class'], dtype='object')

In [7]:
iris.values

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iri

In [8]:
iris.describe(include='all')

sepallength  sepalwidth  petallength  petalwidth        class
count    150.000000  150.000000   150.000000  150.000000          150
unique          NaN         NaN          NaN         NaN            3
top             NaN         NaN          NaN         NaN  Iris-setosa
freq            NaN         NaN          NaN         NaN           50
mean       5.843333    3.054000     3.758667    1.198667          NaN
std        0.828066    0.433594     1.764420    0.763161          NaN
min        4.300000    2.000000     1.000000    0.100000          NaN
25%        5.100000    2.800000     1.600000    0.300000          NaN
50%        5.800000    3.000000     4.350000    1.300000          NaN
75%        6.400000    3.300000     5.100000    1.800000          NaN
max        7.900000    4.400000     6.900000    2.500000          NaN

In [9]:
x=iris.iloc[:,:4]
x.head()

sepallength  sepalwidth  petallength  petalwidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2

In [10]:
y=iris.iloc[:,-1]
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: class, dtype: object

In [11]:
x=preprocessing.StandardScaler().fit_transform(x)
x[0:4]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673]])

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
y_test.shape

(45,)

In [18]:
#training and predicting

knnmodel=KNeighborsClassifier(n_neighbors=3)

In [19]:
knnmodel.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [20]:
KNeighborsClassifier(algorithm='auto',leaf_size=30,metric='minkowski',metric_params=None,n_jobs=None,n_neighbors=3,p=2,
                     weights='uniform')

KNeighborsClassifier(n_neighbors=3)

In [1]:
y_predict1=knnmodel.predict(x_test)

NameError: name 'knnmodel' is not defined

In [22]:
# Accuracy

from sklearn.metrics import accuracy_score

In [23]:
acc=accuracy_score(y_test,y_predict1)
acc

0.9777777777777777

In [25]:
# confusion matrix

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test.values,y_predict1)
cm

array([[14,  0,  0],
       [ 0, 18,  0],
       [ 0,  1, 12]], dtype=int64)

In [27]:
cm1=pd.DataFrame(data=cm,index=['setosa','versicolor','verginica'],columns=['setosa','versicolor','verginica'])
cm1

setosa  versicolor  verginica
setosa          14           0          0
versicolor       0          18          0
verginica        0           1         12

In [2]:
#outputvisualization

prediction_output=pd.DataFrame(data=[y_test.values,y_predict1],index=['y_test','y_predict1'])

NameError: name 'pd' is not defined

In [29]:
prediction_output.transpose()

y_test       y_predict1
0       Iris-setosa      Iris-setosa
1   Iris-versicolor  Iris-versicolor
2   Iris-versicolor  Iris-versicolor
3       Iris-setosa      Iris-setosa
4    Iris-virginica   Iris-virginica
5   Iris-versicolor  Iris-versicolor
6    Iris-virginica   Iris-virginica
7       Iris-setosa      Iris-setosa
8       Iris-setosa      Iris-setosa
9    Iris-virginica   Iris-virginica
10  Iris-versicolor  Iris-versicolor
11      Iris-setosa      Iris-setosa
12   Iris-virginica   Iris-virginica
13  Iris-versicolor  Iris-versicolor
14  Iris-versicolor  Iris-versicolor
15      Iris-setosa      Iris-setosa
16  Iris-versicolor  Iris-versicolor
17  Iris-versicolor  Iris-versicolor
18      Iris-setosa      Iris-setosa
19      Iris-setosa      Iris-setosa
20  Iris-versicolor  Iris-versicolor
21  Iris-versicolor  Iris-versicolor
22  Iris-versicolor  Iris-versicolor
23      Iris-setosa      Iris-setosa
24   Iris-virginica   Iris-virginica
25  Iris-versicolor  Iris-versicolor
26      Iris-setosa      Iris-setosa
27      Iris-setosa      Iris-setosa
28  Iris-versicolor  Iris-versicolor
29   Iris-virginica   Iris-virginica
30  Iris-versicolor  Iris-versicolor
31   Iris-virginica   Iris-virginica
32  Iris-versicolor  Iris-versicolor
33   Iris-virginica   Iris-virginica
34   Iris-virginica   Iris-virginica
35      Iris-setosa      Iris-setosa
36  Iris-versicolor  Iris-versicolor
37      Iris-setosa      Iris-setosa
38  Iris-versicolor  Iris-versicolor
39   Iris-virginica   Iris-virginica
40   Iris-virginica   Iris-virginica
41      Iris-setosa      Iris-setosa
42   Iris-virginica  Iris-versicolor
43   Iris-virginica   Iris-virginica
44  Iris-versicolor  Iris-versicolor

In [30]:
prediction_output.iloc[0,:].value_counts()

Iris-versicolor    18
Iris-setosa        14
Iris-virginica     13
Name: y_test, dtype: int64